var markerImg = {
    redDot: 'https://maps.google.com/mapfiles/ms/icons/red-dot.png',
    blueDot: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png',
    greenDot: 'https://maps.google.com/mapfiles/ms/icons/green-dot.png',
    yellowDot: 'https://maps.google.com/mapfiles/ms/icons/yellow-dot.png',
    orangeDot: 'https://maps.google.com/mapfiles/ms/icons/orange-dot.png',
    pinkDot: 'https://maps.google.com/mapfiles/ms/icons/pink-dot.png',
    purpleDot: 'https://maps.google.com/mapfiles/ms/icons/purple-dot.png',
    ltblueDot: 'https://maps.google.com/mapfiles/ms/icons/ltblue-dot.png',
    red: 'https://maps.google.com/mapfiles/ms/icons/red.png',
    blue: 'https://maps.google.com/mapfiles/ms/icons/blue.png',
    green: 'https://maps.google.com/mapfiles/ms/icons/green.png',
    yellow: 'https://maps.google.com/mapfiles/ms/icons/yellow.png',
    orange: 'https://maps.google.com/mapfiles/ms/icons/orange.png',
    pink: 'https://maps.google.com/mapfiles/ms/icons/pink.png',
    purple: 'https://maps.google.com/mapfiles/ms/icons/purple.png',
    ltblue: 'https://maps.google.com/mapfiles/ms/icons/ltblue.png',
  };